spring.application.name=notifications

#chnaging server port
server.port=8090

# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:userdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#MySql Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/monbuy
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA Configuration
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console Configuration
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.jpa.properties.hibernate.format_sql=true

#JWT Secret Key (256-bit base64-encoded for HS256)
#jwt.Secret=04AWlHolgIqezLFEfVjW2j3YS3tm0eJgiX+IEL+AGJc=
#jwt.Expiration=3600000


